#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Supabase → colist v2 data migration (ticket 11). Runs twice: local
# rehearsal (docker Postgres) and the P5 cutover (prod RDS via scripts/db-tunnel.sh).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE=".env.migration.local"
SUPABASE_REF="zgyllhgyslhshfbfujfu"
WORK_DIR=".migration"
SQL_DIR="scripts/migrate-legacy"
AVATAR_BUCKET="colist-production-uploads"
AVATAR_BASE="https://${AVATAR_BUCKET}.s3.us-east-2.amazonaws.com/avatars"
LOCAL_DB_URL=$(grep -E '^DATABASE_URL=' apps/api/.env.development.local 2>/dev/null | cut -d= -f2- || true)
mkdir -p "$WORK_DIR/avatars"

banner "Supabase → colist v2 data migration"

# ── 1. Source ─────────────────────────────────────────────────────────────
stage "Supabase — connection string"
say "The export reads straight from the old Postgres. Direct connections are IPv6-only, so use the pooler."
open_url "https://supabase.com/dashboard/project/${SUPABASE_REF}?showConnect=true"
step "In the Connect dialog pick Type: URI, Method: Session pooler."
step "Copy the URI and replace [YOUR-PASSWORD] with the database password (Settings → Database → Reset if lost)."
ask_secret SUPABASE_DB_URL "Paste the pooler URI:"
psql "$SUPABASE_DB_URL" -Atc 'select 1' >/dev/null || { warn "could not connect — check the password and try again"; exit 1; }
write_env SUPABASE_DB_URL "$SUPABASE_DB_URL"

# ── 2. Export ─────────────────────────────────────────────────────────────
stage "Export tables → ${WORK_DIR}/*.csv"
export_table() {
  local name="$1" query="$2"
  psql "$SUPABASE_DB_URL" -qc "\\copy ($query) TO '${WORK_DIR}/${name}.csv' CSV HEADER"
  printf '  %s✓%s %-10s %s rows\n' "$GREEN" "$RESET" "$name" "$(( $(wc -l < "${WORK_DIR}/${name}.csv") - 1 ))"
}
export_table users "SELECT id, email, encrypted_password, created_at, updated_at FROM auth.users"
for table in profiles lists members categories items errors feedbacks; do
  export_table "$table" "SELECT * FROM public.${table}"
done
pause

# ── 3. Avatars ────────────────────────────────────────────────────────────
stage "Download avatars → ${WORK_DIR}/avatars/<userId>/<file>"
downloaded=0
while IFS=$'\t' read -r user_id picture; do
  mkdir -p "$WORK_DIR/avatars/$user_id"
  curl -fsS "https://${SUPABASE_REF}.supabase.co/storage/v1/object/public/profiles/${user_id}/${picture}" \
    -o "$WORK_DIR/avatars/$user_id/$picture" && downloaded=$((downloaded + 1)) || warn "missing: $user_id/$picture"
done < <(psql "$SUPABASE_DB_URL" -At -F $'\t' -c "SELECT id, picture FROM public.profiles WHERE picture IS NOT NULL")
say "downloaded $downloaded avatar(s)"
pause

# ── 4. Target ─────────────────────────────────────────────────────────────
stage "Target database"
say "Local rehearsal: the docker Postgres from apps/api/.env.development.local (default)."
say "Cutover: run scripts/db-tunnel.sh in another terminal and paste postgres://…@localhost:5432/…?sslmode=require"
[[ -n "$LOCAL_DB_URL" ]] && write_env DATABASE_URL "$(_existing DATABASE_URL || printf '%s' "$LOCAL_DB_URL")" >/dev/null
ask_secret DATABASE_URL "Target DATABASE_URL:"
psql "$DATABASE_URL" -Atc 'select 1 from "user" limit 1' >/dev/null 2>&1 \
  || { warn "v2 schema missing on the target — boot the API once (bun run dev in apps/api) so it migrates, then re-run"; exit 1; }
write_env DATABASE_URL "$DATABASE_URL"
warn "Loading TRUNCATES every v2 table on the target (users, lists, sessions — everything)."
confirm "Truncate and load into $(sed -E 's#//[^@]*@#//…@#' <<< "$DATABASE_URL")?" || exit 1

# ── 5. Load ───────────────────────────────────────────────────────────────
stage "Load — legacy schema → transform → verify"
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -qf "$SQL_DIR/legacy.sql"
for table in users profiles lists members categories items errors feedbacks; do
  psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -qc "\\copy legacy.${table} FROM '${WORK_DIR}/${table}.csv' CSV HEADER"
done
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -v avatar_base="$AVATAR_BASE" -qf "$SQL_DIR/transform.sql"
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$SQL_DIR/verify.sql"
say "loaded and verified"
pause

# ── 6. Avatars → S3 ───────────────────────────────────────────────────────
stage "Avatars → s3://${AVATAR_BUCKET}/avatars/"
say "user.image already points at ${AVATAR_BASE}/<userId>/<file>. The bucket exists only after the P5 apply."
if confirm "Upload ${WORK_DIR}/avatars to S3 now (needs AWS_PROFILE)?"; then
  aws s3 sync "$WORK_DIR/avatars" "s3://${AVATAR_BUCKET}/avatars/"
else
  SKIPPED+=("aws s3 sync ${WORK_DIR}/avatars s3://${AVATAR_BUCKET}/avatars/ (at P5)")
fi

# ── 7. Smoke ──────────────────────────────────────────────────────────────
stage "Smoke test — sign in with a migrated password"
say "Start the API against the target (apps/api: bun run dev), then sign in as yourself."
ask API_URL "API base URL [http://localhost:5100]:"
API_URL="${API_URL:-http://localhost:5100}"
ask SMOKE_EMAIL "Your colist email:"
ask_secret SMOKE_PASSWORD "Your colist password:"
cookie_jar=$(mktemp)
status=$(curl -s -o /dev/null -w '%{http_code}' -c "$cookie_jar" -H 'content-type: application/json' \
  -d "$(printf '{"email":"%s","password":"%s"}' "$SMOKE_EMAIL" "$SMOKE_PASSWORD")" "$API_URL/api/auth/sign-in/email")
[[ "$status" == "200" ]] || { warn "sign-in returned $status — bcrypt hash or account row is wrong"; exit 1; }
say "signed in ✓ — your lists:"
curl -s -b "$cookie_jar" "$API_URL/api/lists" | tr ',' '\n' | grep -o '"name":"[^"]*"' || warn "no lists returned"
curl -s -b "$cookie_jar" "$API_URL/api/me" | grep -o '"image":"[^"]*"' || true
rm -f "$cookie_jar"

finish
