#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9
ENV_FILE="${ENV_FILE:-.scratch/colist-v2-rebuild/domain-migration.env}"
DOMAIN="heloineto.com"
MAILBOX="hey@heloineto.com"
GMAIL="heloiabreuneto@gmail.com"

banner "Migrate $DOMAIN: GoDaddy → Cloudflare Registrar + Email Routing"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Back up the Titan mailbox"
say "Once DNS moves, $MAILBOX at Titan stops receiving. Save anything you want first."
open_url "https://secureserver.titan.email/mail/"
step "Skim Inbox/Sent for anything worth keeping."
step "Export: Titan has no bulk export in webmail. If you want a full copy, add the"
step "  account to Thunderbird via IMAP (imap.titan.email:993, smtp.titan.email:465)"
step "  and drag folders to Local Folders. Skip if the mailbox is disposable."
step "Note which services use $MAILBOX as login (they'll keep working via forwarding)."
warn "This is the only irreversible data step. Everything after is recoverable."
pause "Backed up (or decided nothing matters)?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — add the zone"
say "Free plan. Cloudflare scans and imports your current records."
open_url "https://dash.cloudflare.com/?to=/:account/add-site"
step "Enter $DOMAIN → Continue → pick Free → Continue."
step "On the DNS review screen, make the record list match EXACTLY this:"
say ""
say "    A      @        76.76.21.21              DNS only (grey cloud, NOT proxied)"
say "    CNAME  www      $DOMAIN                  DNS only"
say "    NS     colist   ns-997.awsdns-60.net"
say "    NS     colist   ns-1436.awsdns-51.org"
say "    NS     colist   ns-1735.awsdns-24.co.uk"
say "    NS     colist   ns-365.awsdns-45.com"
say ""
step "DELETE any MX (secureserver.net), the SPF TXT (include:secureserver.net),"
step "  and the _dmarc TXT — Email Routing replaces these in the next stage."
step "Click Continue. Cloudflare shows two nameservers."
ask CF_NS1 "First Cloudflare nameserver (e.g. xxx.ns.cloudflare.com):"
ask CF_NS2 "Second Cloudflare nameserver:"
write_env CF_NS1 "$CF_NS1"
write_env CF_NS2 "$CF_NS2"
note "Leave the nameserver page open; we change GoDaddy after email routing is set."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — Email Routing"
say "Free forwarding of $MAILBOX → $GMAIL. Cloudflare adds its own MX + SPF."
open_url "https://dash.cloudflare.com/?to=/:account/$DOMAIN/email/routing"
step "Click 'Get started' / Enable Email Routing."
step "Custom address: hey  →  Destination: $GMAIL  → Save."
step "Check Gmail, click the verification link Cloudflare sent."
step "Optional: Catch-all → forward to $GMAIL (catches typos and old aliases)."
step "If prompted 'Add records and enable', accept — it writes MX + SPF TXT."
step "DNS tab: add TXT  _dmarc  →  v=DMARC1; p=reject; adkim=r; aspf=r"
pause "Routing rule active and destination verified?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "GoDaddy — switch nameservers"
open_url "https://dcc.godaddy.com/control/$DOMAIN/dns"
step "Nameservers → Change → 'I'll use my own nameservers'."
step "Enter:  $CF_NS1"
step "        $CF_NS2"
step "Save. Confirm the warning about GoDaddy DNS/email stopping."
pause "Saved?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify DNS at Cloudflare"
say "Propagation is usually minutes for GoDaddy NS changes; sometimes an hour."
check() {
  local label="$1" got; shift; got=$("$@" 2>/dev/null | sort | tr '\n' ' ')
  printf '  %-14s %s\n' "$label" "${got:-<empty>}"
}
until confirm "Run checks now?"; do :; done
while :; do
  say ""
  check "NS"        dig +short NS "$DOMAIN"
  check "A @"       dig +short A "$DOMAIN"
  check "CNAME www" dig +short CNAME "www.$DOMAIN"
  check "NS colist" dig +short NS "colist.$DOMAIN"
  check "MX"        dig +short MX "$DOMAIN"
  check "SPF"       dig +short TXT "$DOMAIN"
  say ""
  say "Expect: NS = the two Cloudflare servers; A = 76.76.21.21; colist = 4× awsdns;"
  say "        MX = route1/2/3.mx.cloudflare.net; SPF includes _spf.mx.cloudflare.net"
  confirm "Looks right?" && break
  pause "Wait a bit, then Enter to re-check"
done
step "Send a test mail from any other account to $MAILBOX; confirm it lands in Gmail."
pause "Test mail received?"
say "Cloudflare dashboard should now show the zone as Active."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "GoDaddy — unlock and get the auth code"
warn "Do NOT edit registrant name/email/org at GoDaddy — that triggers a 60-day transfer lock."
open_url "https://dcc.godaddy.com/control/$DOMAIN/settings"
step "Domain lock → turn OFF."
step "Domain Protection / Privacy → downgrade to none (required to transfer out)."
step "Transfer domain away from GoDaddy → get Authorization code (may be emailed)."
ask_secret EPP_CODE "Paste the authorization (EPP) code:"
note "Not saved to disk — it's single-use and sensitive."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — start the transfer"
open_url "https://dash.cloudflare.com/?to=/:account/domains/transfer"
step "$DOMAIN should be listed as transferable (zone is Active). Select it."
step "Paste the auth code (it's in your clipboard/terminal above)."
step "Confirm contacts, pay ~US\$10.44 (adds 1 year to the current expiry, Feb 2027 → 2028)."
pause "Transfer submitted and paid?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "GoDaddy — approve the transfer out"
say "Skips the 5-day wait."
open_url "https://dcc.godaddy.com/control/transfers"
step "'Transfers out' tab → $DOMAIN → Accept / Approve."
step "Also watch Gmail for a GoDaddy 'transfer request' email with an Accept link."
pause "Approved?"
say "Check registrar (may take minutes):"
until confirm "Run whois now?"; do :; done
while :; do
  if command -v whois >/dev/null; then whois "$DOMAIN" | grep -iE '^ *Registrar:' | head -1
  else warn "whois not installed (sudo apt install whois) — or check https://dash.cloudflare.com → Domain Registration"; fi
  confirm "Shows Cloudflare?" && break
  pause "Wait, then Enter to re-check"
done

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "GoDaddy — stop the bleeding"
open_url "https://account.godaddy.com/renewals"
step "Email Profissional Individual ($MAILBOX) → Auto-renew OFF (charges 28/03/2027 otherwise)."
step "$DOMAIN → should be gone from the list; if still there, Auto-renew OFF."
step "Optionally remove the saved payment method."
pause "Done?"
say "Titan mailbox keeps working for login until it lapses in March 2027; it no longer receives mail."
say "Sending from $MAILBOX: Gmail 'Send mail as' dies Jan 2027 — if you ever need it,"
say "  Zoho Mail free tier or Purelymail (~US\$10/yr) are the cheap options."

finish
