#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — AWS production setup (tickets 12/13). Run from repo root:
#   bash scripts/setup-aws-prod.sh            # P1 sitting: state bucket + bootstrap, then stops
#   bash scripts/setup-aws-prod.sh --resume   # P5 sitting: production apply → secrets → cutover prep
# ──────────────────────────────────────────────────────────────────────────

[[ "$ENV_FILE" == ".env" ]] && ENV_FILE=".scratch/colist-v2-rebuild/aws-prod.env"  # library defaults to .env
mkdir -p "$(dirname "$ENV_FILE")"
RESUME=0; [[ "${1:-}" == "--resume" ]] && RESUME=1
TOTAL_STAGES=$(( RESUME ? 10 : 4 ))
export AWS_PROFILE="${AWS_PROFILE:-voto-a-voto}" AWS_REGION=us-east-2
ACCOUNT_EXPECTED=547279162914
STATE_BUCKET=colist-tfstate
PROD=iac/environments/production
HOST=colist.heloineto.com
SSM_PREFIX=/colist/production/api

banner "AWS production setup: ${HOST}"

stage "AWS credentials (SSO, profile $AWS_PROFILE)"
until [[ "$(aws sts get-caller-identity --query Account --output text 2>/dev/null)" == "$ACCOUNT_EXPECTED" ]]; do
  warn "not signed in to account $ACCOUNT_EXPECTED as profile $AWS_PROFILE."
  step "Run: aws sso login --profile $AWS_PROFILE   (in another terminal, or now)"
  confirm "Run it here?" && aws sso login --profile "$AWS_PROFILE" || pause "Press Enter to re-check"
done
write_env AWS_ACCOUNT_ID "$ACCOUNT_EXPECTED"
pause

stage "Terraform state bucket ($STATE_BUCKET)"
say "Hand-created, never declared in Terraform. Versioned + encrypted + private."
if aws s3api head-bucket --bucket "$STATE_BUCKET" 2>/dev/null; then
  note "bucket already exists — reusing"
else
  aws s3api create-bucket --bucket "$STATE_BUCKET" --region "$AWS_REGION" \
    --create-bucket-configuration LocationConstraint="$AWS_REGION" >/dev/null
  aws s3api put-bucket-versioning --bucket "$STATE_BUCKET" --versioning-configuration Status=Enabled
  aws s3api put-bucket-encryption --bucket "$STATE_BUCKET" \
    --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
  aws s3api put-public-access-block --bucket "$STATE_BUCKET" \
    --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true
  note "created $STATE_BUCKET"
fi
write_env TF_STATE_BUCKET "$STATE_BUCKET"
pause

stage "Bootstrap stack (OIDC provider + CI roles)"
say "Applied by a human with admin creds, never by CI. Review the plan before typing 'yes'."
bun run iac:bootstrap:init
bun run iac:bootstrap:apply
pause

stage "GitHub: AWS_ACCOUNT_ID variable + main branch protection"
say "The PR plan job (iac.yml) needs the account id to build the role ARN. Only the read-only"
say "plan role is usable until main.yml runs — and nothing merges to main before the P5 sitting."
set_var AWS_ACCOUNT_ID "$ACCOUNT_EXPECTED"
say "Protect main: PR required, Lint + Test checks required, no direct pushes."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh api -X PUT "repos/{owner}/{repo}/branches/main/protection" --input - >/dev/null <<'JSON' \
    && note "main protected" || { SKIPPED+=("branch protection on main (Settings → Branches)"); warn "couldn't set branch protection"; }
{"required_status_checks":{"strict":true,"contexts":["Lint","Test"]},"enforce_admins":false,
 "required_pull_request_reviews":null,"restrictions":null,"allow_force_pushes":false,"allow_deletions":false}
JSON
else
  SKIPPED+=("branch protection on main (Settings → Branches)"); warn "gh not ready — protect main by hand later"
fi
pause

if (( ! RESUME )); then
  finish
  say "P1 sitting done. Everything past this point costs money (EC2 + RDS) — resume at P5 with:"
  note "    bash scripts/setup-aws-prod.sh --resume"
  exit 0
fi

# ────────────────────────────── P5 sitting ──────────────────────────────

stage "Production stack: init + import the hosted zone"
say "Zone $HOST was hand-created in ticket 20; import it so Terraform owns it (prevent_destroy)."
ZONE_ID=$(grep -E '^ROUTE53_ZONE_ID=' .scratch/colist-v2-rebuild/route53.env | cut -d= -f2)
terraform -chdir="$PROD" init -input=false
if terraform -chdir="$PROD" state list 2>/dev/null | grep -q '^aws_route53_zone.this$'; then
  note "zone already in state"
else
  terraform -chdir="$PROD" import aws_route53_zone.this "$ZONE_ID"
fi
write_env ROUTE53_ZONE_ID "$ZONE_ID"
pause

stage "Production stack: first apply (by hand; CI owns it afterwards)"
warn "This creates the EC2 instance and RDS — billing starts now. The ECS service stays pending until the first image push."
terraform -chdir="$PROD" apply -input=false
write_env EIP_PUBLIC_IP "$(terraform -chdir="$PROD" output -raw eip_public_ip)"
write_env INSTANCE_ID "$(terraform -chdir="$PROD" output -raw instance_id)"
pause

stage "session-manager-plugin (SSM port-forward client)"
until command -v session-manager-plugin >/dev/null 2>&1; do
  warn "session-manager-plugin not installed."
  open_url "https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html"
  step "Install it for your OS (Ubuntu: download the .deb from that page, sudo dpkg -i)."
  pause "Press Enter to re-check"
done
note "$(session-manager-plugin --version 2>/dev/null || echo installed)"
say "Verify later with: scripts/db-tunnel.sh  (then psql/DBeaver → localhost:5432, sslmode=require)."
pause

stage "SSM secrets ($SSM_PREFIX/*)"
say "Assemble DATABASE_URL from the RDS-managed master secret; generate BETTER_AUTH_SECRET; reuse the"
say "Google OAuth client from ticket 19 (its prod origin/redirect were added in ticket 20)."
secret_arn=$(terraform -chdir="$PROD" output -raw db_master_user_secret_arn)
db_host=$(terraform -chdir="$PROD" output -raw db_address)
db_json=$(aws secretsmanager get-secret-value --secret-id "$secret_arn" --query SecretString --output text)
db_user=$(printf '%s' "$db_json" | jq -r .username)
db_pass=$(printf '%s' "$db_json" | jq -r '.password|@uri')
DATABASE_URL="postgres://${db_user}:${db_pass}@${db_host}:5432/postgres?sslmode=require&sslrootcert=/app/rds-ca.pem"
BETTER_AUTH_SECRET=$(openssl rand -base64 32)
GOOGLE_CLIENT_ID=$(grep -E '^GOOGLE_CLIENT_ID=' apps/api/.env.development.local | cut -d= -f2- || true)
GOOGLE_CLIENT_SECRET=$(grep -E '^GOOGLE_CLIENT_SECRET=' apps/api/.env.development.local | cut -d= -f2- || true)
[[ -n "$GOOGLE_CLIENT_ID" ]]     || ask GOOGLE_CLIENT_ID "Google client id (console.cloud.google.com/auth/clients → colist-web):"
[[ -n "$GOOGLE_CLIENT_SECRET" ]] || ask_secret GOOGLE_CLIENT_SECRET "Google client secret:"
for name in DATABASE_URL BETTER_AUTH_SECRET GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET; do
  if aws ssm get-parameter --name "$SSM_PREFIX/$name" >/dev/null 2>&1 && ! confirm "$name already set — overwrite?"; then
    note "kept $name"; continue
  fi
  aws ssm put-parameter --name "$SSM_PREFIX/$name" --type SecureString --overwrite --value "${!name}" >/dev/null
  printf '  %s✓ set%s %s\n' "$GREEN" "$RESET" "$SSM_PREFIX/$name"
done
note "Values live only in SSM (and your password manager) — never in git or CI."
pause

stage "Freeze the old app: 'legacy' tag + Vercel disconnect"
say "Tag the frozen Next app so it stays reachable, then stop Vercel from building main."
if git rev-parse -q --verify refs/tags/legacy >/dev/null; then
  note "tag legacy exists"
else
  git fetch origin main:refs/remotes/origin/main >/dev/null 2>&1 || true
  git tag legacy origin/main && git push origin legacy
  note "tagged origin/main as legacy"
fi
open_url "https://vercel.com/dashboard"
step "Open the colist project → Settings → Git → Disconnect."
note "The last production deployment keeps serving until cutover; main is now safe to merge into."
pause

stage "First deploy + smoke test"
say "Open the PR dev → main and merge it. main.yml applies, builds both images and rolls the service."
step "Watch: gh run watch   (or the Actions tab)"
pause "Press Enter once the Main workflow is green"
until curl -fsS "https://${HOST}/health" >/dev/null 2>&1; do
  warn "https://${HOST}/health not answering yet (Caddy needs a minute for the Let's Encrypt cert)."
  confirm "Retry?" || { SKIPPED+=("smoke: curl https://${HOST}/health"); break; }
  sleep 20
done
curl -fsS "https://${HOST}/health" 2>/dev/null | sed 's/^/    /' || true
say "Then: sign-up, SSE, Google login (consent still in Testing). Next: data migration (ticket 11)."
pause

finish
