CREATE TABLE "public"."feedbacks"(
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "created" timestamp with time zone NOT NULL DEFAULT NOW(),
  "message" jsonb,
  "files" text array,
  "rating" integer CHECK ("rating" >= 1 AND "rating" <= 5),
  "profileId" uuid DEFAULT auth.uid() REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE SET NULL
);

ALTER TABLE "public"."feedbacks" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable ALL if profileId is the auth id" ON "public"."feedbacks" AS permissive
  FOR ALL TO authenticated
    USING ((SELECT auth.uid()) = "profileId")
    WITH CHECK ((SELECT auth.uid()) = "profileId");
