CREATE TABLE "public"."categories"(
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "created" timestamp with time zone NOT NULL DEFAULT NOW(),
  "name" text NOT NULL,
  "listId" bigint NOT NULL REFERENCES "public"."lists"("id") ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "grant ALL if the user is a member of the category's list"
ON "public"."categories"
FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM "public"."members"
    WHERE
      "public"."members"."listId" = "public"."categories"."listId"
      AND "public"."members"."profileId" = (SELECT auth.uid())
  )
);