CREATE TABLE "public"."lists"(
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "created" timestamp with time zone NOT NULL DEFAULT NOW(),
  "name" text NOT NULL CHECK (char_length("name") >= 1)
);

ALTER TABLE "public"."lists" ENABLE ROW LEVEL SECURITY;

ALTER publication supabase_realtime ADD TABLE "public"."lists";