CREATE TABLE "public"."items"(
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "created" timestamp with time zone NOT NULL DEFAULT NOW(),
  "name" text NOT NULL,
  "amount" integer NOT NULL CHECK ("amount" >= 0) DEFAULT 1,
  "checked" boolean NOT NULL DEFAULT FALSE,
  "details" text,
  "categoryId" bigint REFERENCES "public"."categories"("id") ON UPDATE CASCADE ON DELETE SET NULL,
  "listId" bigint NOT NULL REFERENCES "public"."lists"("id") ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE "public"."items" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "grant ALL if the user is a member of the item's list"
ON "public"."items"
FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM "public"."members"
    WHERE
      "public"."members"."listId" = "public"."items"."listId"
      AND "public"."members"."profileId" = (SELECT auth.uid())
  )
);

ALTER publication supabase_realtime ADD TABLE "public"."items";